-- Violet Bloom: Supabase schema + RLS
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.bouquets (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(12,2) not null default 0 check (price >= 0),
  category text not null default 'Авторские',
  image_url text,
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  comment text,
  payment_method text not null default 'Картой при получении',
  total_price numeric(12,2) not null default 0 check (total_price >= 0),
  status text not null default 'new' check (status in ('new','confirmed','preparing','delivery','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  bouquet_id bigint not null references public.bouquets(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  price numeric(12,2) not null check (price >= 0)
);

create index if not exists idx_bouquets_category on public.bouquets(category);
create index if not exists idx_bouquets_available on public.bouquets(available);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order on public.order_items(order_id);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists bouquets_updated_at on public.bouquets;
create trigger bouquets_updated_at before update on public.bouquets for each row execute function public.set_updated_at();
drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin insert into public.profiles(id,email,name,role) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'name','Пользователь'),'user') on conflict(id) do update set email=excluded.email; return new; end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.bouquets enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin');
$$;

-- Drop/recreate policies safely
 drop policy if exists "public read available bouquets" on public.bouquets;
 drop policy if exists "admins manage bouquets" on public.bouquets;
 drop policy if exists "authenticated create orders" on public.orders;
 drop policy if exists "admins read orders" on public.orders;
 drop policy if exists "admins update orders" on public.orders;
 drop policy if exists "admins delete orders" on public.orders;
 drop policy if exists "admins read order items" on public.order_items;
 drop policy if exists "authenticated insert order items" on public.order_items;
 drop policy if exists "users read own profile" on public.profiles;
 drop policy if exists "users update own profile" on public.profiles;
 drop policy if exists "admins read profiles" on public.profiles;
 drop policy if exists "admins update profiles" on public.profiles;

create policy "public read available bouquets" on public.bouquets for select using (available=true or public.is_admin());
create policy "admins manage bouquets" on public.bouquets for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "authenticated create orders" on public.orders for insert to anon,authenticated with check (true);
create policy "admins read orders" on public.orders for select to authenticated using (public.is_admin());
create policy "admins update orders" on public.orders for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete orders" on public.orders for delete to authenticated using (public.is_admin());

create policy "authenticated insert order items" on public.order_items for insert to anon,authenticated with check (true);
create policy "admins read order items" on public.order_items for select to authenticated using (public.is_admin());

create policy "users read own profile" on public.profiles for select to authenticated using (auth.uid()=id or public.is_admin());
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);
create policy "admins read profiles" on public.profiles for select to authenticated using (public.is_admin());
create policy "admins update profiles" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.bouquets(name,description,price,category,image_url,available) values
('Фиолетовый рассвет','Нежная авторская композиция с фиолетовыми акцентами.',3900,'Авторские','./assets/violet-bloom-01.svg',true),
('Лавандовый сад','Спокойная композиция для тёплого и красивого жеста.',3200,'Авторские','./assets/violet-bloom-02.svg',true),
('Белая классика','Минималистичный букет в светлой гамме.',4500,'Классика','./assets/violet-bloom-03.svg',true),
('Розовый акцент','Яркий букет для дня рождения и особых случаев.',4100,'Классика','./assets/violet-bloom-04.svg',true),
('Свадебная дымка','Лёгкая композиция для церемонии и фотосессии.',6900,'Свадебные','./assets/violet-bloom-05.svg',true),
('Полевой вечер','Натуральный букет с ощущением летнего сада.',3600,'Авторские','./assets/violet-bloom-06.svg',true),
('Виолетта','Композиция в фирменной фиолетовой гамме.',4900,'Авторские','./assets/violet-bloom-07.jpg',true),
('Маленький комплимент','Небольшой букет, когда хочется сказать много.',2200,'Мини','./assets/violet-bloom-08.jpg',true),
('Утренний букет','Светлые цветы и свежая зелень.',3500,'Мини','./assets/violet-bloom-09.svg',true),
('Праздничный пурпур','Выразительная композиция для большого события.',5900,'Классика','./assets/violet-bloom-10.svg',true);

-- Storage bucket. If the bucket already exists, the insert may be skipped manually in dashboard.
insert into storage.buckets(id,name,public) values('bouquets','bouquets',true) on conflict(id) do update set public=true;
